# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            volumes:
                - ${{ github.workspace }}/CA:/CA
                - ${{ github.workspace }}/Untrusted:/Untrusted
        steps:
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
            - name: VERIFY CERTIFICATES 2
              run: echo ${{ github.workspace }}
            - name: VERIFY CERTIFICATES 3
              run: pwd