# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            options: -v $GITHUB_WORKSPACE/CA:/CA/:rw -v $GITHUB_WORKSPACE/Untrusted:/Untrusted/:rw
        steps:
            - name: VERIFY CERTIFICATES 1
              run: pwd
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
               