# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            volumes:
                - ${{ github.workspace }}/CA:/CA:ro
                - ${{ github.workspace }}/Untrusted:/Untrusted:ro
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - run: ls CA/
            - run: pwd
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
               