# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            options: "-v /__w/cert-verify/cert-verify/CA:/CA/:rw -v /__w/cert-verify/cert-verify/Untrusted:/Untrusted/:rw"
        steps:
            - name: VERIFY CERTIFICATES 1
              run: pwd
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
               