# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    my-job:
        runs-on: ubuntu-latest
        container:
            volumes:
                - ${{ github.workspace }}/CA:/CA
                - ${{ github.workspace }}/Untrusted:/Untrusted
        steps:
            - uses: docker://mirkotp/cert-verify
        