# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        # container:
        #     image: 'mirkotp/cert-verify:latest'
        #     volumes:
        #         - ${{ github.workspace }}/CA:/CA
        #         - ${{ github.workspace }}/Untrusted:/Untrusted
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: VERIFY CERTIFICATES
              run: | 
                docker pull mirkotp/cert-verify
                docker run -v ${{ github.workspace }}/CA:/CA -v ${{ github.workspace }}/Untrusted:/Untrusted mirkotp/cert-verify