# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            volumes:
                - /__w/cert-verify/cert-verify/CA:${{ github.workspace }}/CA/
                - /__w/cert-verify/cert-verify/Untrusted:${{ github.workspace }}/Untrusted
        steps:
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
               