# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        # container:
        #     image: 'mirkotp/cert-verify:latest'
        #     volumes:
        #         - ${{ github.workspace }}/CA:/CA
        #         - ${{ github.workspace }}/Untrusted:/Untrusted
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - uses: addnab/docker-run-action@v3
              with:
                image: mirkotp/cert-verify:latest
                options: -v ${{ github.workspace }}/CA:/CA -v ${{ github.workspace }}/Untrusted:/Untrusted
                run: sh /entry.sh