# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        container:
            image: 'mirkotp/cert-verify'
            volumes:
                - ./CA:/CA
                - ./Untrusted:/Untrusted
        steps:
            - name: VERIFY CERTIFICATES
              run: sh /entry.sh
