# main.yml
name: Certificate check
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: VERIFY CERTIFICATES
              run: | 
                docker pull -q mirkotp/cert-verify > /dev/null
                docker run -q -v ${{ github.workspace }}/CA:/CA -v ${{ github.workspace }}/Untrusted:/Untrusted mirkotp/cert-verify
