# main.yml
name: CI
on:
  push:
    branches: [ main ]
jobs:
    container-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: VERIFY CERTIFICATES
              uses: docker://mirkotp/cert-verify:latest
              with:
                args: >-
                    -v ${{ github.workspace }}/CA:/CA
                    -v ${{ github.workspace }}/Untrusted:/Untrusted
               